name: Output example ## Workflow name
run-name: Workflow Input example, ran by ${{ github.actor }} # Name when running
on:
  workflow_dispatch: 

jobs:
  output-generating:
    runs-on: ubuntu-latest
    steps:
      ## Output using shell
      - name: Generating Output with Shell
        id: output-example
        run: |
          ACTION_RANDOM=$(( $RANDOM ))
          echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT
      - name: Displaying action's output
        run: echo "${{ steps.output-example.outputs.action_random }}"